version: '3.7'

volumes:
    logs:
        driver: local

services:
    php:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        environment:
            docker: "true"
            PHP_MEMORY_LIMIT: '128M'
            XDEBUG_SESSION: 'PHPSTORM'
        volumes:
            - .:/www
            - logs:/www/logs
            - .docker/php/php.ini:/usr/local/etc/php/php.ini
            - .docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    httpd:
        build:
            context: .
            dockerfile: .docker/httpd/Dockerfile
        ports:
            - 8088:80
        volumes:
            - .:/www
            - .docker/httpd/apache.conf:/usr/local/apache2/conf/web.apache.conf
        links:
            - php
    database:
        image: mysql:5.7
        ports:
            - 13306:3306
        volumes:
            - ./mysql-data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: 'my_app'
            MYSQL_USER: 'dbuser'
            MYSQL_PASSWORD: 'dbUs3r!'
            MYSQL_ROOT_PASSWORD: 'root'
        #volumes_from:
        #  - container:<container_name>
